### ISSUE TITLE
HDF5 saving error

### ISSUE THREAD

**Issue by HamidL** [BNN-UPC/ignnition#50]
After correctly training I am receiving the following error: 

NotImplementedError: Saving the model to HDF5 format requires the model to be a Functional model or a Sequential model. It does not work for subclassed models, because such models are defined via the body of a Python method, which isn't safely serializable. Consider saving to the Tensorflow SavedModel format (by setting save_format="tf") or using `save_weights`.

The full traceback is the following:

`Traceback (most recent call last):
  File "main_ignnition.py", line 7, in <module>
    model.train_and_validate()
  File "[...]/.pyenv/versions/miniconda3-latest/envs/py38/lib/python3.8/site-packages/ignnition/ignnition_model.py", line 678, in train_and_validate
    self.gnn_model.fit(train_dataset,
  File "[...]/.pyenv/versions/miniconda3-latest/envs/py38/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 1229, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "[...]/.pyenv/versions/miniconda3-latest/envs/py38/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 435, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "[...]/.pyenv/versions/miniconda3-latest/envs/py38/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 1369, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "[...]/.pyenv/versions/miniconda3-latest/envs/py38/lib/python3.8/site-packages/tensorflow/python/keras/callbacks.py", line 1433, in _save_model
    self.model.save(filepath, overwrite=True, options=self._options)
  File "[...]/.pyenv/versions/miniconda3-latest/envs/py38/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 2111, in save
    save.save_model(self, filepath, overwrite, include_optimizer, save_format,
  File "[...]/.pyenv/versions/miniconda3-latest/envs/py38/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 139, in save_model
    raise NotImplementedError(
NotImplementedError: Saving the model to HDF5 format requires the model to be a Functional model or a Sequential model. It does not work for subclassed models, because such models are defined via the body of a Python method, which isn't safely serializable. Consider saving to the Tensorflow SavedModel format (by setting save_format="tf") or using `save_weights`.
`

Is there a parameter that must be defined to solve this issue?

**Comment by davidpujol** [comment]
Dear HamidL,
Thanks for your interest in IGNNITION.

For reproducibility purposes, would you be so kind to provide the concrete Python and TensorFlow version that you are using to execute your model?

Best,
David

**Comment by HamidL** [comment]
Dear David,

I'm currently using Python 3.8.5 and TensorFlow 2.5.0
I'm using that version of TF due to a CUDA error related (or at least, that's what I think) with TF 2.3.0 and the RTX 30 series cards (more details here https://github.com/tensorflow/tensorflow/issues/43701).

Best,
Hamid.

**Comment by davidpujol** [comment]
Dear Hamid,

Unfortunately IGNNITION does not yet have support for TensorFlow 2.5.0. 
We are currently working on fixing this issue, so please stay tuned for new releases of IGNNITION.

Best,
David
