### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'replace' " when using convolution as aggregation

### ISSUE THREAD

**Issue by ognjenkundacina** [BNN-UPC/ignnition#91]
Hello!

When I try to use convolution as an aggregation function I get an error listed at the bottom of this issue. I'm not sure if there are some prerequirements that should be satisfied before using convolutions. Message passing stage looks like:

    - stage_message_passings:
      - destination_entity: variableNode
        source_entities:
          - name: factorNode
            message:
              - type: direct_assignment
        aggregation:
          - type: convolution
        update:
          type: neural_network
          nn_name: recurrent1

You can find the whole code here, if needed: 
[code.zip](https://github.com/BNN-UPC/ignnition/files/7352558/code.zip)

Best regards,

Ognjen

Epoch 1/1000
100/100 [==============================] - 8s 40ms/step - loss: 0.0266 - mean_absolute_error: 0.1001 - val_loss: 0.0027 - val_mean_absolute_error: 0.0316
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    main()
  File "main.py", line 11, in main
    model.train_and_validate()
  File "C:\Users\OgnjenKundacina\miniconda3\envs\gnn_env\lib\site-packages\ignnition\ignnition_model.py", line 751, in train_and_validate
    verbose=1)
  File "C:\Users\OgnjenKundacina\miniconda3\envs\gnn_env\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1145, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\OgnjenKundacina\miniconda3\envs\gnn_env\lib\site-packages\tensorflow\python\keras\callbacks.py", line 428, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\OgnjenKundacina\miniconda3\envs\gnn_env\lib\site-packages\tensorflow\python\keras\callbacks.py", line 1344, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)
  File "C:\Users\OgnjenKundacina\miniconda3\envs\gnn_env\lib\site-packages\tensorflow\python\keras\callbacks.py", line 1406, in _save_model
    filepath, overwrite=True, options=self._options)
  File "C:\Users\OgnjenKundacina\miniconda3\envs\gnn_env\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2124, in save_weights
    self._trackable_saver.save(filepath, session=session, options=options)
  File "C:\Users\OgnjenKundacina\miniconda3\envs\gnn_env\lib\site-packages\tensorflow\python\training\tracking\util.py", line 1217, in save
    file_prefix_tensor, object_graph_tensor, options)
  File "C:\Users\OgnjenKundacina\miniconda3\envs\gnn_env\lib\site-packages\tensorflow\python\training\tracking\util.py", line 1154, in _save_cached_when_graph_building
    object_graph_tensor=object_graph_tensor)
  File "C:\Users\OgnjenKundacina\miniconda3\envs\gnn_env\lib\site-packages\tensorflow\python\training\tracking\util.py", line 1120, in _gather_saveables
    feed_additions) = self._graph_view.serialize_object_graph()
  File "C:\Users\OgnjenKundacina\miniconda3\envs\gnn_env\lib\site-packages\tensorflow\python\training\tracking\graph_view.py", line 408, in serialize_object_graph
    trackable_objects, path_to_root)
  File "C:\Users\OgnjenKundacina\miniconda3\envs\gnn_env\lib\site-packages\tensorflow\python\training\tracking\graph_view.py", line 363, in _serialize_gathered_objects
    object_names[obj] = _object_prefix_from_path(path)
  File "C:\Users\OgnjenKundacina\miniconda3\envs\gnn_env\lib\site-packages\tensorflow\python\training\tracking\graph_view.py", line 64, in _object_prefix_from_path
    for trackable in path_to_root))
  File "C:\Users\OgnjenKundacina\miniconda3\envs\gnn_env\lib\site-packages\tensorflow\python\training\tracking\graph_view.py", line 64, in <genexpr>
    for trackable in path_to_root))
  File "C:\Users\OgnjenKundacina\miniconda3\envs\gnn_env\lib\site-packages\tensorflow\python\training\tracking\graph_view.py", line 57, in _escape_local_name
    return (name.replace(_ESCAPE_CHAR, _ESCAPE_CHAR + _ESCAPE_CHAR)
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by MiquelFerriol** [comment]
Hi again @ognjenkundacina!

This problem was related to the last issue you created, where there was an error with the weights saving. This problem has been fixed in #92. Upgrading IGNNITION to the last versions (1.3.3) should fix it.

Thanks again for your time posting those issues.

Bests,
Miquel

**Comment by ognjenkundacina** [comment]
The problem doesn't reproduce anymore. Thanks!

Best regards,
Ognjen
